[package]
name = "keymapper"
version = "0.0.1"
authors = [ "Dmitry Golubets <dgolubets@gmail.com>" ]
include = [ "src/application.conf" ]

[dependencies]
config = "0.1.2"
winapi = "0.2.4"
user32-sys = "0.1.2"
