# Scan this file for changes every 30 seconds
refresh_rate = "30s"

# An appender named "console" that writes to stdout
[appenders]
[appenders.console]
kind = "console"

[appenders.file]
kind = "file"
path = "application.log"
encoder.pattern = "%d [%t] %l %M:%m"

[root]
level = "trace"
appenders = ["console", "file"]
